name=input("Enter your name: ")
family=input("Enter your family: ")
age=input("Enter your age: ")
a=float(input("enter mark of math: "))
b=float(input("Enter mark of dini: "))
c=float(input("enter mark of farsi: "))
print("Hello,",name,family,"you are",age,"years old and your GPA",(a+b+c)/3)